name: social_design_system
description: "Elegant UI/UX design library crafted specifically for building social like applications"
version: 0.0.5
homepage: https://thruthesky.github.io/social_design_system
repository: https://github.com/thruthesky/social_design_system

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  loop_page_view: ^1.2.5
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
